jobs/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from jobs.sitemaps import Sitemaps, StaticViewSitemap

schema_view = get_schema_view(
    openapi.Info(
        title="Jobs Portal API",
        default_version="v1",
        description="Jobs Portal Api Description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

lang_patterns = i18n_patterns(
    path("", include("jobsapp.urls")),
    path("", include("accounts.urls")),
)

# sitemaps = {
#     '': JobViewSitemap
# }

urlpatterns = lang_patterns + [
    url(r"^i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path(
        "api/",
        include(
            [
                path("swagger", schema_view.with_ui("swagger", cache_timeout=0)),
                path("", include("accounts.api.urls")),
                path("", include("jobsapp.api.urls")),
                path("", include("tags.api.urls")),
                # path('auth/oauth/', include('rest_framework_social_oauth2.urls'))
            ]
        ),
    ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    # url(r"^(?P<url>.*/)$", flatpages_views.flatpage),
    path("sitemap.xml/", sitemap, {"sitemaps": dict(Sitemaps())}, name="django.contrib.sitemaps.views.sitemap"),
]

jobsapp/urls.py
from django.urls import include, path

from .views import *

app_name = "jobs"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("favorite/", favorite, name="favorite"),
    path("search/", SearchView.as_view(), name="search"),
    path(
        "employer/dashboard/",
        include(
            [
                path("", DashboardView.as_view(), name="employer-dashboard"),
                path(
                    "all-applicants/",
                    ApplicantsListView.as_view(),
                    name="employer-all-applicants",
                ),
                path(
                    "applicants/<int:job_id>/",
                    ApplicantPerJobView.as_view(),
                    name="employer-dashboard-applicants",
                ),
                path(
                    "applied-applicant/<int:job_id>/view/<int:applicant_id>",
                    AppliedApplicantView.as_view(),
                    name="applied-applicant-view",
                ),
                path("mark-filled/<int:job_id>/", filled, name="job-mark-filled"),
                path("send-response/<int:applicant_id>", SendResponseView.as_view(), name="applicant-send-response"),
                path("jobs/create/", JobCreateView.as_view(), name="employer-jobs-create"),
                path("jobs/<int:id>/edit/", JobUpdateView.as_view(), name="employer-jobs-edit"),
            ]
        ),
    ),
    path(
        "employee/",
        include(
            [
                path(
                    "my-applications",
                    EmployeeMyJobsListView.as_view(),
                    name="employee-my-applications",
                ),
                path("favorites", FavoriteListView.as_view(), name="employee-favorites"),
            ]
        ),
    ),
    path("apply-job/<int:job_id>/", ApplyJobView.as_view(), name="apply-job"),
    path("jobs/", JobListView.as_view(), name="jobs"),
    path("jobs/<int:id>/", JobDetailsView.as_view(), name="jobs-detail"),
]

jobsapp/api/views/employer.py
from django.http import JsonResponse
from rest_framework.generics import CreateAPIView, ListAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView

from jobsapp.api.permissions import IsEmployer, IsJobCreator
from jobsapp.api.serializers import (
    ApplicantSerializer,
    DashboardJobSerializer,
    NewJobSerializer,
)
from jobsapp.models import Applicant


class DashboardAPIView(ListAPIView):
    serializer_class = DashboardJobSerializer
    permission_classes = [IsAuthenticated, IsEmployer]

    def get_queryset(self):
        return self.serializer_class.Meta.model.objects.filter(user_id=self.request.user.id)


class JobCreateAPIView(CreateAPIView):
    serializer_class = NewJobSerializer
    permission_classes = [IsAuthenticated, IsEmployer]


class ApplicantsListAPIView(ListAPIView):
    serializer_class = ApplicantSerializer
    permission_classes = [IsAuthenticated, IsEmployer]

    def get_queryset(self):
        user = self.request.user
        return Applicant.objects.filter(job__user_id=user.id)


class ApplicantsPerJobListAPIView(ListAPIView):
    serializer_class = ApplicantSerializer
    permission_classes = [IsAuthenticated, IsEmployer, IsJobCreator]

    def get_queryset(self):
        return Applicant.objects.filter(job_id=self.kwargs["job_id"]).order_by("id")


class UpdateApplicantStatusAPIView(APIView):
    permission_classes = [IsAuthenticated, IsEmployer]

    def post(self, request, *args, **kwargs):
        applicant_id = kwargs.get("applicant_id")
        status_code = kwargs.get("status_code")
        try:
            applicant = Applicant.objects.select_related("job__user").get(id=applicant_id)
        except Applicant.DoesNotExist:
            data = {"message": "Applicant not found"}
            return JsonResponse(data, status=404)

        if applicant.job.user != request.user:
            data = {"errors": "You are not authorized"}
            return JsonResponse(data, status=403)
        if status_code not in [1, 2]:
            status_code = 3

        applicant.status = status_code
        applicant.comment = request.data.get("comment", "")
        applicant.save()
        data = {"message": "Applicant status updated"}
        return JsonResponse(data, status=200)

jobsapp/views/employer.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from accounts.forms import EmployerProfileUpdateForm
from jobsapp.decorators import user_is_employer
from jobsapp.forms import CreateJobForm
from jobsapp.models import Applicant, Job
from tags.models import Tag


class DashboardView(ListView):
    model = Job
    template_name = "jobs/employer/dashboard.html"
    context_object_name = "jobs"

    @method_decorator(login_required(login_url=reverse_lazy("accounts:login")))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user_id=self.request.user.id)


class ApplicantPerJobView(ListView):
    model = Applicant
    template_name = "jobs/employer/applicants.html"
    context_object_name = "applicants"
    paginate_by = 6

    @method_decorator(login_required(login_url=reverse_lazy("accounts:login")))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Applicant.objects.filter(job_id=self.kwargs["job_id"]).order_by("id")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["job"] = Job.objects.get(id=self.kwargs["job_id"])
        return context


class JobCreateView(CreateView):
    template_name = "jobs/create.html"
    form_class = CreateJobForm
    extra_context = {"title": "Post New Job"}
    success_url = reverse_lazy("jobs:employer-dashboard")

    @method_decorator(login_required(login_url=reverse_lazy("accounts:login")))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy("accounts:login")
        if self.request.user.is_authenticated and self.request.user.role != "employer":
            return reverse_lazy("accounts:login")
        return super().dispatch(self.request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(JobCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


@method_decorator(login_required(login_url=reverse_lazy("accounts:login")), name="dispatch")
@method_decorator(user_is_employer, name="dispatch")
class JobUpdateView(UpdateView):
    template_name = "jobs/update.html"
    form_class = CreateJobForm
    extra_context = {"title": "Edit Job"}
    slug_field = "id"
    slug_url_kwarg = "id"
    success_url = reverse_lazy("jobs:employer-dashboard")
    context_object_name = "job"

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Job.objects.filter(user_id=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "Job updated successfully")
        return super(JobUpdateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class ApplicantsListView(ListView):
    model = Applicant
    template_name = "jobs/employer/all-applicants.html"
    context_object_name = "applicants"

    @method_decorator(login_required(login_url=reverse_lazy("accounts:login")))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        # jobs = Job.objects.filter(user_id=self.request.user.id)
        # return self.model.objects.filter(job__user_id=self.request.user.id)
        self.queryset = self.model.objects.filter(job__user_id=self.request.user.id).order_by("id")
        if "status" in self.request.GET and len(self.request.GET.get("status")) > 0:
            self.queryset = self.queryset.filter(status=int(self.request.GET.get("status")))
        return self.queryset


@login_required(login_url=reverse_lazy("accounts:login"))
@user_is_employer
def filled(request, job_id=None):
    try:
        job = Job.objects.get(user_id=request.user.id, id=job_id)
        job.filled = True
        job.save()
    except IntegrityError as e:
        return HttpResponseRedirect(reverse_lazy("jobs:employer-dashboard"))
    return HttpResponseRedirect(reverse_lazy("jobs:employer-dashboard"))


@method_decorator(login_required(login_url=reverse_lazy("accounts:login")), name="dispatch")
@method_decorator(user_is_employer, name="dispatch")
class AppliedApplicantView(DetailView):
    model = Applicant
    template_name = "jobs/employer/applied-applicant-view.html"
    context_object_name = "applicant"
    slug_field = "id"
    slug_url_kwarg = "applicant_id"

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Applicant.objects.select_related("job").filter(job_id=self.kwargs["job_id"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@method_decorator(login_required(login_url=reverse_lazy("accounts:login")), name="dispatch")
@method_decorator(user_is_employer, name="dispatch")
class SendResponseView(UpdateView):
    model = Applicant
    http_method_names = ["post"]
    pk_url_kwarg = "applicant_id"
    fields = ("status", "comment")

    def get_success_url(self):
        return reverse_lazy(
            "jobs:applied-applicant-view",
            kwargs={"job_id": self.request.POST.get("job_id"), "applicant_id": self.get_object().id},
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.status != request.POST.get("status"):
            if request.POST.get("status") == "1":
                status = "Pending"
            elif request.POST.get("status") == "2":
                status = "Accepted"
            else:
                status = "Rejected"
            messages.success(self.request, "Response was successfully sent")
            # notify_candidate_about_job_status_change.delay(self.object.user.get_full_name(), self.object.user.email, self.object.job.id, self.object.job.title, status)
        else:
            messages.warning(self.request, "Response already sent")
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        pk = self.kwargs.get(self.pk_url_kwarg)
        queryset = queryset.filter(pk=pk)
        try:
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(
                "No %(verbose_name)s found matching the query" % {"verbose_name": queryset.model._meta.verbose_name}
            )
        return obj


class EmployerProfileEditView(UpdateView):
    form_class = EmployerProfileUpdateForm
    context_object_name = "employer"
    template_name = "jobs/employer/edit-profile.html"
    success_url = reverse_lazy("accounts:employer-profile-update")

    @method_decorator(login_required(login_url=reverse_lazy("accounts:login")))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            raise Http404("User doesn't exists")
        return self.render_to_response(self.get_context_data())

    def get_object(self, queryset=None):
        obj = self.request.user
        if obj is None:
            raise Http404("Job doesn't exists")
        return obj

templates/jobs/employer/applied-applicant-view.html
{% extends 'base.html' %}
{% block title %}
    Applicants
{% endblock %}
{% load static %}
{% block styles %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.3.200/pdf_viewer.css"/>
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}"/>

    <style>
        * {
            margin: 0;
            padding: 0;
        }

        .top-bar {
            background: #333;
            color: #fff;
            padding: 1rem;
        }

        .btn-pdf {
            background: coral;
            color: #fff;
            border: none;
            outline: none;
            cursor: pointer;
            padding: 0.7rem 2rem;
        }

        .btn-pdf:hover {
            opacity: 0.9;
        }

        .page-info {
            margin-left: 1rem;
        }

        .error {
            background: orangered;
            color: #fff;
            padding: 1rem;
        }
    </style>

{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">{{ applicant.user.get_full_name }}</h1>
                    <h6 class="heading">Applied for: {{ applicant.job.title }}</h6>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    {% if applicant.cv.name %}
                        <div class="top-bar hidden">
                            <button class="btn btn-pdf" id="prev-page">
                                <i class="fa fa-arrow-circle-left"></i> Prev Page
                            </button>
                            <button class="btn btn-pdf" id="next-page">
                                Next Page <i class="fa fa-arrow-circle-right"></i>
                            </button>
                            <span class="page-info">
                            Page <span id="page-num"></span> of <span id="page-count"></span>
                        </span>
                        </div>

                        <canvas id="pdf-render"></canvas>
                    {% else %}
                        <h3>CV not available</h3>
                    {% endif %}
                </div>
                <div class="col-lg-4">
                    <h4>About: {{ applicant.user.get_full_name }}</h4>
                    <h6>Skills:
                        {% for tag in applicant.user.profile.tags.all %}
                            <span style="color: #ffffff;"
                                  class="badge featured-badge badge-secondary">{{ tag.name }}
                            </span>
                        {% endfor %}
                    </h6>
                    <h6>Gender: {{ applicant.user.gender }}</h6>
                    <h6>Email: {{ applicant.user.email }}</h6>
                    <h6 class="text-success">Status: {% if applicant.status == 1 %}
                        Pending {% elif applicant.status == 2 %} Accepted {% elif applicant.status == 3 %}
                        Rejected {% endif %}</h6>
                    <p class="job-detail__company-description">{{ job.company_description }}</p>
                    <p class="job-detail__social social social--outline">
                        <a href="{{ job.website }}" data-toggle="tooltip" data-placement="top" title="Website"
                           class="link">
                            <i class="fa fa-link"></i>
                        </a>
                    </p>
                    <input type="button" class="btn btn-outline-white-primary" {% if applicant.status != 1 %}
                           disabled {% endif %} value="Send Response" data-toggle="modal"
                           data-target="#myModal"/>
                </div>
                {% if applicant.status == 1 %}
                    <div class="modal fade" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">

                                <div class="modal-header">
                                    <h4 class="modal-title">Send response</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <form action="{% url 'jobs:applicant-send-response' applicant.id %}" method="POST">
                                    {% csrf_token %}
                                    <div class="modal-body">
                                        <input type="hidden" name="job_id" value="{{ applicant.job.id }}">
                                        <div class="form-group">
                                            <label for="status">Status</label>
                                            <select id="status" name="status" class="form-control">
                                                <option value="2" {% if applicant.status == 2 %} selected
                                                        disabled {% endif %}>
                                                    Accepted
                                                </option>
                                                <option value="3" {% if applicant.status == 3 %} selected
                                                        disabled {% endif %}>
                                                    Rejected
                                                </option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="Comment">Comment</label>
                                            <textarea id="Comment" name="comment" rows="3" required
                                                      class="form-control">{{ applicant.comment|default_if_none:"" }}</textarea>
                                        </div>
                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                        <input type="submit" class="btn btn-success" value="Send"/>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Dashboard
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Dashboard</h1>
                    <p class="lead text-center">All created jobs</p>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-right mb-5">
                    <a href="{% url 'jobs:employer-jobs-create' %}" class="btn btn-outline-white-primary">
                        <i class="fa fa-plus"></i>Add new position
                    </a>
                </div>
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-client-dashboard">
                            <thead>
                            <tr>
                                <th>Job title</th>
                                <th>Position filled</th>
                                <th>Date posted</th>
                                <th>Date expiring</th>
                                <th>Applicants</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for job in jobs %}

                                <tr>
                                    <th><a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a>
                                    </th>
                                    <td>
                                        {% if job.filled %}
                                            <span class="badge badge-success">Filled</span>
                                        {% else %}
                                            <span class="badge badge-secondary">Not Filled</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ job.created_at }}</td>
                                    <td>{{ job.last_date }}</td>
                                    <td>
                                        <a href="{% url 'jobs:employer-dashboard-applicants' job.id %}"
                                           class="btn btn-success">
                                            <i class="fa fa-users"></i>{{ job.applicants.count }}
                                            <span class="hidden-xs hidden-sm">Applicants</span>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'jobs:employer-jobs-edit' job.id %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i>Edit
                                        </a>
                                        <br>
                                        {% if job.filled %}
                                            <a href="{% url 'jobs:job-mark-filled' job.id %}"
                                               class="btn btn-outline-white-secondary">
                                                <i class="fa fa-check-circle-o"></i>
                                                <span class="hidden-xs hidden-sm">Filled</span>
                                            </a><br>
                                        {% else %}
                                            <a href="{% url 'jobs:job-mark-filled' job.id %}"
                                               class="btn btn-outline-white-secondary">
                                                <i class="fa fa-check-circle-o"></i>
                                                <span class="hidden-xs hidden-sm">Mark as </span>filled
                                            </a><br>
                                        {% endif %}
                                        <a href="#" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-times-circle-o"></i>Delete
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="pages">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                <li class="page-item"><a href="#" aria-label="Previous" class="page-link"><span
                                        aria-hidden="true">«</span><span class="sr-only">Previous</span></a></li>
                                <li class="page-item active"><a href="#" class="page-link">1</a></li>
                                <li class="page-item"><a href="#" class="page-link">2</a></li>
                                <li class="page-item"><a href="#" class="page-link">3</a></li>
                                <li class="page-item"><a href="#" class="page-link">4</a></li>
                                <li class="page-item"><a href="#" aria-label="Next" class="page-link"><span
                                        aria-hidden="true">»</span><span class="sr-only">Next</span></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/edit-profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}
    <div class="col-lg-6 offset-3">
        <div class="box">
            <h3 class="heading">Edit Company Profile</h3>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}"
                               class="form-control"
                               name="{{ field.name }}"
                               id="id_{{ field.name }}"
                               value="{{ field.value }}"
                               placeholder="{{ field.field.widget.attrs.placeholder }}">
                    </div>
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-white-primary">
                        <i class="fa fa-signing"></i> Update
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}