accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from jobsapp.views import EditProfileView, EmployerProfileEditView

from .views import *

app_name = "accounts"

urlpatterns = [
    path("employee/register/", RegisterEmployeeView.as_view(), name="employee-register"),
    path("employer/register/", RegisterEmployerView.as_view(), name="employer-register"),
    path(
        "employee/profile/update/",
        EditProfileView.as_view(),
        name="employee-profile-update",
    ),
    path(
        "employer/profile/update/",
        EmployerProfileEditView.as_view(),
        name="employer-profile-update",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(), name="login"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from jobs.sitemaps import Sitemaps, StaticViewSitemap

schema_view = get_schema_view(
    openapi.Info(
        title="Jobs Portal API",
        default_version="v1",
        description="Jobs Portal Api Description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

lang_patterns = i18n_patterns(
    path("", include("jobsapp.urls")),
    path("", include("accounts.urls")),
)

# sitemaps = {
#     '': JobViewSitemap
# }

urlpatterns = lang_patterns + [
    url(r"^i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path(
        "api/",
        include(
            [
                path("swagger", schema_view.with_ui("swagger", cache_timeout=0)),
                path("", include("accounts.api.urls")),
                path("", include("jobsapp.api.urls")),
                path("", include("tags.api.urls")),
                # path('auth/oauth/', include('rest_framework_social_oauth2.urls'))
            ]
        ),
    ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    # url(r"^(?P<url>.*/)$", flatpages_views.flatpage),
    path("sitemap.xml/", sitemap, {"sitemaps": dict(Sitemaps())}, name="django.contrib.sitemaps.views.sitemap"),
]

jobsapp/urls.py
from django.urls import include, path

from .views import *

app_name = "jobs"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("favorite/", favorite, name="favorite"),
    path("search/", SearchView.as_view(), name="search"),
    path(
        "employer/dashboard/",
        include(
            [
                path("", DashboardView.as_view(), name="employer-dashboard"),
                path(
                    "all-applicants/",
                    ApplicantsListView.as_view(),
                    name="employer-all-applicants",
                ),
                path(
                    "applicants/<int:job_id>/",
                    ApplicantPerJobView.as_view(),
                    name="employer-dashboard-applicants",
                ),
                path(
                    "applied-applicant/<int:job_id>/view/<int:applicant_id>",
                    AppliedApplicantView.as_view(),
                    name="applied-applicant-view",
                ),
                path("mark-filled/<int:job_id>/", filled, name="job-mark-filled"),
                path("send-response/<int:applicant_id>", SendResponseView.as_view(), name="applicant-send-response"),
                path("jobs/create/", JobCreateView.as_view(), name="employer-jobs-create"),
                path("jobs/<int:id>/edit/", JobUpdateView.as_view(), name="employer-jobs-edit"),
            ]
        ),
    ),
    path(
        "employee/",
        include(
            [
                path(
                    "my-applications",
                    EmployeeMyJobsListView.as_view(),
                    name="employee-my-applications",
                ),
                path("favorites", FavoriteListView.as_view(), name="employee-favorites"),
            ]
        ),
    ),
    path("apply-job/<int:job_id>/", ApplyJobView.as_view(), name="apply-job"),
    path("jobs/", JobListView.as_view(), name="jobs"),
    path("jobs/<int:id>/", JobDetailsView.as_view(), name="jobs-detail"),
]

jobsapp/views/home.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView
from rest_framework.decorators import api_view

from ..documents import JobDocument
from ..forms import ApplyJobForm
from ..models import Applicant, Favorite, Job


class HomeView(ListView):
    model = Job
    template_name = "home.html"
    context_object_name = "jobs"

    def get_queryset(self):
        return self.model.objects.unfilled()[:6]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["trendings"] = self.model.objects.unfilled(created_at__month=timezone.now().month)[:3]
        return context


class SearchView(ListView):
    model = Job
    template_name = "jobs/search.html"
    context_object_name = "jobs"

    def get_queryset(self):
        # q = JobDocument.search().query("match", title=self.request.GET['position']).to_queryset()
        # print(q)
        # return q
        return self.model.objects.filter(
            location__contains=self.request.GET.get("location", ""),
            title__contains=self.request.GET.get("position", ""),
        )


class JobListView(ListView):
    model = Job
    template_name = "jobs/jobs.html"
    context_object_name = "jobs"
    paginate_by = 5


class JobDetailsView(DetailView):
    model = Job
    template_name = "jobs/details.html"
    context_object_name = "job"
    pk_url_kwarg = "id"

    def get_object(self, queryset=None):
        obj = super(JobDetailsView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Job doesn't exists")
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            # raise error
            raise Http404("Job doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class ApplyJobView(CreateView):
    model = Applicant
    form_class = ApplyJobForm
    slug_field = "job_id"
    slug_url_kwarg = "job_id"

    @method_decorator(login_required(login_url=reverse_lazy("accounts:login")))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            messages.info(self.request, "Successfully applied for the job!")
            return self.form_valid(form)
        else:
            return HttpResponseRedirect(reverse_lazy("jobs:home"))

    def get_success_url(self):
        return reverse_lazy("jobs:jobs-detail", kwargs={"id": self.kwargs["job_id"]})

    # def get_form_kwargs(self):
    #     kwargs = super(ApplyJobView, self).get_form_kwargs()
    #     print(kwargs)
    #     kwargs['job'] = 1
    #     return kwargs

    def form_valid(self, form):
        # check if user already applied
        applicant = Applicant.objects.filter(user_id=self.request.user.id, job_id=self.kwargs["job_id"])
        if applicant:
            messages.info(self.request, "You already applied for this job")
            return HttpResponseRedirect(self.get_success_url())
        # save applicant
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


def favorite(request):
    if not request.user.is_authenticated:
        return JsonResponse(data={"auth": False, "status": "error"})

    job_id = request.POST.get("job_id")
    user_id = request.user.id
    try:
        fav = Favorite.objects.get(job_id=job_id, user_id=user_id, soft_deleted=False)
        if fav:
            fav.soft_deleted = True
            fav.save()
            # fav.delete()
            return JsonResponse(
                data={
                    "auth": True,
                    "status": "removed",
                    "message": "Job removed from your favorite list",
                }
            )
    except Favorite.DoesNotExist:
        Favorite.objects.create(job_id=job_id, user_id=user_id)
        return JsonResponse(
            data={
                "auth": True,
                "status": "added",
                "message": "Job added to your favorite list",
            }
        )

templates/base.html
{% load static %}
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %} {% endblock %} - Django Jobs</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet"
          href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
          href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    {% block styles %}{% endblock %}
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
<!-- navbar-->
{% csrf_token %}
<header class="header">
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a href="{% url 'jobs:home' %}" class="navbar-brand">
                <img src="{% static 'img/logo-small.png' %}" alt="logo" class="d-none d-lg-block">
                <span class="sr-only">Home</span>
            </a>
            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">
                {% with request.resolver_match.url_name as url_name %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {% if url_name == 'home' %}active{% endif %}">
                        <a href="{% url 'jobs:home' %}" class="nav-link">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item {% if url_name == 'jobs' %}active{% endif %}">
                        <a href="{% url 'jobs:jobs' %}" class="nav-link">Jobs</a>
                    </li>
                    <li class="nav-item">
                        <a href="/{{ LANGUAGE_CODE }}/about-us/" class="nav-link">About Us</a>
                    </li>
                    {% if request.user.is_authenticated and request.user.role == 'employer' %}
                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                <div class="client-menu-image">
                                    <div class="inner">
                                        <img src="{% static 'img/company-1.png' %}"
                                             alt="company image"
                                             class="img-fluid">
                                    </div>
                                </div>
                                {% if request.user.role == 'employee' %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a 
                                    href="{% url 'jobs:employer-dashboard' %}" 
                                    class="dropdown-item {% if url_name == 'employer-dashboard' %}active{% endif %}"
                                >
                                    Dashboard
                                </a>
                                <a 
                                    href="{% url 'jobs:employer-all-applicants' %}" 
                                    class="dropdown-item {% if url_name == 'employer-all-applicants' %}active{% endif %}"
                                >
                                    Applicants 
                                </a>
                                <a 
                                    href="{% url 'jobs:employer-jobs-create' %}" 
                                    class="dropdown-item {% if url_name == 'employer-jobs-create' %}active{% endif %}"
                                >
                                    Post a new job 
                                </a>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    {% elif request.user.is_authenticated and request.user.role == 'employee' %}
                        <li class="nav-item {% if url_name == 'employee-favorites' %}active{% endif %}">
                            <a href="{% url 'jobs:employee-favorites' %}" class="nav-link">Favorites</a>
                        </li>
                        <li class="nav-item {% if url_name == 'employee-my-applications' %}active{% endif %}">
                            <a href="{% url 'jobs:employee-my-applications' %}" class="nav-link">My Applications</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                <div class="client-menu-image">
                                    <div class="inner">
                                        <img src="{% static 'img/company-1.png' %}"
                                             alt="company image"
                                             class="img-fluid">
                                    </div>
                                </div>
                                {% if request.user.role == 'employee' %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a 
                                    href="{% url 'accounts:employee-profile-update' %}" 
                                    class="dropdown-item {% if url_name == 'employee-profile-update' %}active{% endif %}"
                                >
                                    Edit Profile
                                </a>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown {% if url_name == 'employee-register' or url_name == 'employer-register' %}active{% endif %}">
                            <a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle "><i class="fa fa-signing"></i>Register
                            </a>
                            <div aria-labelledby="pages" class="dropdown-menu">
                                <a 
                                    href="{% url 'accounts:employee-register' %}" 
                                    class="dropdown-item {% if url_name == 'employee-register' %}active{% endif %}"
                                >
                                    Employee
                                </a>
                                <a 
                                    href="{% url 'accounts:employer-register' %}" 
                                    class="dropdown-item {% if url_name == 'employer-register' %}active{% endif %}"
                                >
                                    Employers
                                </a>
                            </div>
                        </li>
                        <li class="nav-item" style="color: #fff">
                            <a 
                                href="{% url 'accounts:login' %}" 
                                class="btn navbar-btn btn-outline-light mb-5 mb-lg-0 {% if url_name == 'login' %}active text-primary{% endif %}"
                            >
                                <i class="fa fa-sign-in"></i>
                                Login
                            </a>
                        </li>
                    {% endif %}
                    {% include "lang_selector.html" %}
                </ul>
                {% endwith %}
            </div>
        </div>
    </nav>
</header>
<div>
    {% if messages %}

        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {#            <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>#}
        {% endfor %}

    {% endif %}
    {% block content %} {% endblock %}
</div>
<footer class="footer">
    <div class="footer__block">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 mb-5">
                    <h4 class="h5">About django-jobs</h4>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis
                        aliquet congue. </p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer__copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-4 text-md-left text-center">
                    <p>&copy;{% now "Y" %} django-jobs!</p>
                </div>
                <div class="col-md-8 text-center text-md-right github-buttons">
                    <a href="https://github.com/manjurulhoque/django-job-portal" target="_blank" rel="noopener">
                        <img alt="stars" src="https://img.shields.io/github/stars/manjurulhoque/django-job-portal?style=social"/>
                    </a>
                    <a href="https://github.com/manjurulhoque/django-job-portal" target="_blank" rel="noopener">
                        <img alt="forks" src="https://img.shields.io/github/forks/manjurulhoque/django-job-portal?style=social"/>
                    </a>
                    <a href="https://github.com/manjurulhoque/django-job-portal/issues" target="_blank" rel="noopener">
                        <img alt="issues" src="https://img.shields.io/github/issues/manjurulhoque/django-job-portal?style=social"/>
                    </a>
                    <a href="https://github.com/manjurulhoque/django-job-portal/#contributors-" target="_blank" rel="noopener">
                        <img alt="translation" src="https://img.shields.io/badge/all_contributors-18-orange.svg?style=flat-square"/>
                    </a>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
{% block javascripts %}{% endblock %}

<script type="text/javascript">
    function changeLanguage(event) {
    }
</script>

</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
    Home
{% endblock %}

{% block content %}

    <section class="job-form-section job-form-section--image">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job-form-box">
                        <h2 class="heading">Find a <span class="accent">job</span> you will
                            <span class="accent">love</span>.
                        </h2>
                        <form id="job-main-form" method="get" action="{% url 'jobs:search' %}" class="job-main-form">
                            <div class="controls">
                                <div class="row align-items-center">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="profession">{% trans 'Position' %}</label>
                                            <input type="text" id="profession" name="position"
                                                   placeholder="Position you are looking for" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="location">Location</label>
                                            <input type="text" id="location" name="location"
                                                   placeholder="Any particular location?" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <button type="submit"
                                                class="btn btn-outline-white-primary job-main-form__button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="bg-light-gray">
        <div class="container">
            <h3 class="heading">Featured jobs</h3>
            <div class="row featured align-items-stretch">
                {% for job in jobs %}
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="box-image-text bg-visible full-height">
                            <div class="top">
                                <a href="#">
                                    <div class="image">
                                        <img src="{% static 'img/featured1.jpg' %}" alt="" class="img-fluid">
                                    </div>
                                    <div class="bg"></div>
                                    <div class="logo">
                                        <img src="{% static 'img/company-1.png' %}" alt="" style="max-width: 80px;">
                                    </div>
                                </a>
                            </div>
                            <div class="content">
                                <h5><a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a></h5>
                                <p class="featured__details"><i class="fa fa-map-marker job__location"></i>
                                    {{ job.location }}
                                    {% if job.type == '1' %}
                                        <span class="badge featured-badge badge-success">Full time</span>
                                    {% elif job.type == '2' %}
                                        <span class="badge featured-badge badge-primary">Part time</span>
                                    {% else %}
                                        <span style="color: #ffffff;" class="badge featured-badge badge-warning">Internship</span>
                                    {% endif %}
                                </p>
                                {% for tag in job.tags.all %}
                                    <span style="color: #ffffff;"
                                          class="badge featured-badge badge-secondary">{{ tag.name }}</span>
                                {% endfor %}
                                <p>{{ job.description }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <h4 class="heading">Trending this month</h4>
            {% for trending in trendings %}
                <div class="job-listing  job-listing--last">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/company-1.png' %}"
                                         alt="ShareBoardd " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title">
                                        <a href="{% url 'jobs:jobs-detail' trending.id %}">{{ trending.title }}</a>
                                    </h4>
                                    <p class="job__company">
                                        {{ trending.company_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                            {{ trending.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ trending.created_at|timesince }}</p>
                        </div>
                        <div class="col-sm-12 col-md-2 col-lg-1">
                            <div class="job__star">
                                <a href="#" data-toggle="tooltip" data-placement="top"
                                   title="Save to favourites" class="job__star__link">
                                    <i class="fa fa-star"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
    <section class="section-divider">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Start searching for your new job now! </p>
                    <p><a href="{% url 'jobs:jobs' %}" class="btn btn-outline-light">See our job offers </a></p>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/lang_selector.html
{% load i18n %}
{% get_available_languages as languages %}
{% get_current_language as LANGUAGE_CODE %}

<li class="nav-item dropdown">
    <a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
       class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
        <em class="fa fa-language"></em>
        {% trans "Language" %}
    </a>

    <form action="{% url 'set_language' %}" method="post" id="change-language-form">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}">
    </form>

    <div aria-labelledby="clientZone" class="dropdown-menu">
        {% for lang_code, lang_name in languages %}
            {% language lang_code %}
                <a href="{% url "jobs:home" %}" data-lang-code="{{ lang_code }}" class="dropdown-item">{{ lang_name }}</a>
            {% endlanguage %}
        {% endfor %}
    </div>
</li>