jobs/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from jobs.sitemaps import Sitemaps, StaticViewSitemap

schema_view = get_schema_view(
    openapi.Info(
        title="Jobs Portal API",
        default_version="v1",
        description="Jobs Portal Api Description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

lang_patterns = i18n_patterns(
    path("", include("jobsapp.urls")),
    path("", include("accounts.urls")),
)

# sitemaps = {
#     '': JobViewSitemap
# }

urlpatterns = lang_patterns + [
    url(r"^i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path(
        "api/",
        include(
            [
                path("swagger", schema_view.with_ui("swagger", cache_timeout=0)),
                path("", include("accounts.api.urls")),
                path("", include("jobsapp.api.urls")),
                path("", include("tags.api.urls")),
                # path('auth/oauth/', include('rest_framework_social_oauth2.urls'))
            ]
        ),
    ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    # url(r"^(?P<url>.*/)$", flatpages_views.flatpage),
    path("sitemap.xml/", sitemap, {"sitemaps": dict(Sitemaps())}, name="django.contrib.sitemaps.views.sitemap"),
]

jobsapp/urls.py
from django.urls import include, path

from .views import *

app_name = "jobs"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("favorite/", favorite, name="favorite"),
    path("search/", SearchView.as_view(), name="search"),
    path(
        "employer/dashboard/",
        include(
            [
                path("", DashboardView.as_view(), name="employer-dashboard"),
                path(
                    "all-applicants/",
                    ApplicantsListView.as_view(),
                    name="employer-all-applicants",
                ),
                path(
                    "applicants/<int:job_id>/",
                    ApplicantPerJobView.as_view(),
                    name="employer-dashboard-applicants",
                ),
                path(
                    "applied-applicant/<int:job_id>/view/<int:applicant_id>",
                    AppliedApplicantView.as_view(),
                    name="applied-applicant-view",
                ),
                path("mark-filled/<int:job_id>/", filled, name="job-mark-filled"),
                path("send-response/<int:applicant_id>", SendResponseView.as_view(), name="applicant-send-response"),
                path("jobs/create/", JobCreateView.as_view(), name="employer-jobs-create"),
                path("jobs/<int:id>/edit/", JobUpdateView.as_view(), name="employer-jobs-edit"),
            ]
        ),
    ),
    path(
        "employee/",
        include(
            [
                path(
                    "my-applications",
                    EmployeeMyJobsListView.as_view(),
                    name="employee-my-applications",
                ),
                path("favorites", FavoriteListView.as_view(), name="employee-favorites"),
            ]
        ),
    ),
    path("apply-job/<int:job_id>/", ApplyJobView.as_view(), name="apply-job"),
    path("jobs/", JobListView.as_view(), name="jobs"),
    path("jobs/<int:id>/", JobDetailsView.as_view(), name="jobs-detail"),
]

templates/jobs/details.html
{% extends 'base.html' %}
{% load static %}
{% load is_already_applied %}
{% load humanize %}
{% block title %}
    Job details
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <h1 class="heading">{{ job.title }}<br>
                <small>at <a href="#"> {{ job.company_name }}</a></small>
            </h1>
            <div class="job-detail-description"><i class="fa fa-map-marker job__location"> </i>
                {{ job.location }} | Posted {{ job.created_at|timesince }} |
                {% if job.type == '1' %}
                    <span class="badge featured-badge badge-success">Full time</span>
                {% elif job.type == '2' %}
                    <span class="badge featured-badge badge-primary">Part time</span>
                {% else %}
                    <span style="color: #ffffff;" class="badge featured-badge badge-warning">Internship</span>
                {% endif %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <h3>Category: {{ job.category }}</h3>
                    <h5>Last date: {{ job.last_date|date }}</h5>
                    <h5 class="text-info">Salary: {% if job.salary > 0 %} {{ job.salary | intcomma}}/Monthly {% else %} Negotiable {% endif %} </h5>
                    Tags:
                    {% for tag in job.tags.all %}
                        <span style="color: #ffffff;" class="badge featured-badge badge-secondary">{{ tag.name }}</span>
                    {% endfor %}
                    <blockquote class="blockquote">
                        <p>{{ job.description }}</p>
                    </blockquote>
                    <div class="job-detail__apply-bottom">
                        {% if request.user.is_authenticated %}
                            {% is_already_applied job request.user as is_applied %}
                            {% if is_applied %}
                                <input type="button" class="btn btn-outline-white-primary" value="Already applied"/>
                            {% else %}
                                <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="job" value="{{ job.id }}">
                                    <input type="submit" class="btn btn-outline-white-primary"
                                           value="Apply for this job"/>
                                </form>
                            {% endif %}
                        {% else %}
                            <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="job" value="{{ job.id }}">
                                <input type="submit" class="btn btn-outline-white-primary"
                                       value="Apply for this job"/>
                            </form>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-1"></div>
                <div class="col-lg-3">
                    <h4>About {{ job.company_name }}</h4>
                    <p class="job-detail__company-description">{{ job.company_description }}</p>
                    <p class="job-detail__social social social--outline">
                        <a href="{{ job.website }}" data-toggle="tooltip" data-placement="top" title="Website"
                           class="link">
                            <i class="fa fa-link"></i>
                        </a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter" class="twitter">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook" class="facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                    <div class="job-detail__apply-top">
                        {% if is_applied %}
                            <input type="button" class="btn btn-outline-white-primary" value="Already applied"/>
                        {% else %}
                            <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="job" value="{{ job.id }}">
                                <input type="submit" class="btn btn-outline-white-primary" value="Apply for this job"/>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/jobs.html
{% extends 'base.html' %}
{% load static %}
{% load is_favorited %}
{% block title %}
    All jobs
{% endblock %}

{% block content %}

    <section class="job-form-section job-form-section--compressed">
        <div class="container">
            <h4 class="heading">Find a <span class="accent">job </span> you will <span class="accent">love</span></h4>
            <form id="job-main-form" method="get" class="job-main-form">
                <div class="controls">
                    <div class="row align-items-end">
                        <div class="col-sm-1 col-lg-2"></div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="profession">Profession</label>
                            <input type="text" id="profession" name="profession"
                                   placeholder="Profession you are looking for" class="form-control">
                        </div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="location">Location</label>
                            <input type="text" id="location" name="location" placeholder="Any particular location?"
                                   value="" class="form-control">
                        </div>
                        <div class="col-sm-1 col-lg-2 form-group">
                            <button type="submit" class="btn btn-outline-white-primary job-main-form__button">
                                <i class="fa fa-search"></i> Search
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <section>
        <div class="container">
            <h3 class="heading">We have found <span class="accent">{{ jobs.count }}</span> jobs</h3>
            {% for job in jobs %}
                <div class="job-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/company-1.png' %}"
                                         alt="Ipsioou " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title"><a
                                            href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a></h4>
                                    <p class="job__company">
                                        {{ job.company_name }}
                                    </p>
                                    {% for tag in job.tags.all %}
                                        <span style="color: #ffffff;" class="badge featured-badge badge-secondary">{{ tag.name }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                            {{ job.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ job.created_at|timesince }}</p>
                        </div>
                        {% if user.is_authenticated and request.user.role == 'employee' %}
                            <div class="col-sm-12 col-md-2 col-lg-1">
                                <div class="job__star">
                                    {% is_favorited job as is_already_favorited %}
                                    {% if is_already_favorited %}
                                        <a href="javascript:void(0)" data-toggle="tooltip" data-id="{{ job.id }}"
                                           data-placement="top" title="Saved to favourites"
                                           class="job__star__link favorite">
                                            <i class="fa fa-star"></i>
                                        </a>
                                    {% else %}
                                        <a href="javascript:void(0)" data-toggle="tooltip" data-id="{{ job.id }}"
                                           data-placement="top" title="Save to favourites" class="job__star__link">
                                            <i class="fa fa-star"></i>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}

{% block javascripts %}

    <script>
        let csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        $('.job__star__link').on('click', function () {
            let job_id = $(this).data('id');
            let that = $(this);
            $.ajax({
                type: "POST",
                url: "{% url 'jobs:favorite' %}",
                data: {job_id},
                success: function (res, textStatus, xhr) {
                    if (res.status === "added") {
                        that.addClass('favorite');
                        toastr.success(res.message);
                    } else if (res.status === "removed") {
                        document.activeElement.blur();
                        that.removeClass('favorite');
                        toastr.warning(res.message);
                    }
                },
                error: function (err, textStatus, xhr) {
                    if (xhr === "Unauthorized") {
                        toastr.error("Unauthorized");
                    } else {
                        toastr.error("Something wrong");
                    }
                }
            })
        });
    </script>

{% endblock %}

templates/jobs/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    All jobs
{% endblock %}

{% block content %}

    <section class="job-form-section job-form-section--compressed">
        <div class="container">
            <h4 class="heading">Find a <span class="accent">job </span> you will <span class="accent">love</span></h4>
            <form id="job-main-form" method="get" action="#" class="job-main-form">
                <div class="controls">
                    <div class="row align-items-end">
                        <div class="col-sm-1 col-lg-2"></div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="profession">Position</label>
                            <input type="text" id="position" name="position"
                                   placeholder="Position you are looking for" class="form-control">
                        </div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="location">Location</label>
                            <input type="text" id="location" name="location" placeholder="Any particular location?"
                                   value="" class="form-control">
                        </div>
                        <div class="col-sm-1 col-lg-2 form-group">
                            <button type="submit" name="name"
                                    class="btn btn-outline-white-primary job-main-form__button">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <section>
        <div class="container">
            <h3 class="heading">We have found <span class="accent">{{ jobs.count }}</span> jobs</h3>
            {% for job in jobs %}
                <div class="job-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/company-1.png' %}"
                                         alt="Ipsioou " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title"><a
                                            href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a></h4>
                                    <p class="job__company">
                                        {{ job.company_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                            {{ job.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ job.created_at|timesince }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}